# Generated by Django 6.0.6 on 2026-09-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drink_riceextra_ricetype_shawarmaextra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemsize',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
