# Generated by Django 6.0.6 on 2026-07-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drink_riceextra_ricetype_shawarmaextra_and_more'),
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='rice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ricetype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shawarma_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.shawarmaoption'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitemsize'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rice_type_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shawarma_option_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shawarma_option_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='OrderItemDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='order.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemRiceExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_extra', to='order.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemShawarmaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_added', models.BooleanField(default=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawarma_extra', to='order.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='order.cartitem')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drink')),
            ],
            options={
                'unique_together': {('cart_item', 'drink')},
            },
        ),
        migrations.CreateModel(
            name='CartItemRiceExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_extras', to='order.cartitem')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.riceextra')),
            ],
            options={
                'unique_together': {('cart_item', 'extra')},
            },
        ),
        migrations.CreateModel(
            name='CartItemShawarmaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_added', models.BooleanField(default=False)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawarma_extra', to='order.cartitem')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.shawarmaextra')),
            ],
            options={
                'unique_together': {('cart_item', 'extra')},
            },
        ),
    ]
