# Generated by Django 6.0.6 on 2026-07-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemshawarmaextra',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawarma_extras', to='order.cartitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shawarma_option_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitemriceextra',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rice_extras', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitemshawarmaextra',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shawarma_extras', to='order.orderitem'),
        ),
    ]
