# Generated by Django 6.0.6 on 2026-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartitemshawarmaextra_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
