# Generated by Django 6.0.6 on 2026-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
