# Generated by Django 6.0.6 on 2026-08-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drink_riceextra_ricetype_shawarmaextra_and_more'),
        ('order', '0008_orderitem_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shawarma_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.shawarmaoption'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitemsize'),
        ),
    ]
