# Generated by Django 6.0.6 on 2026-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_cartitem_shawarma_option_alter_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
